name: Validate Pull Request
on:
  pull_request:
    branches:
      - 'develop'
      - 'master'
      - 'rc'

# Concurrency strategy:
#   github.workflow: distinguish this workflow from others
#   github.event_name: distinguish `push` event from `pull_request` event
#   github.ref_name: distinguish branch
#   github.repository: distinguish owner+repository
#
# Reference:
#   https://docs.github.com/en/actions/using-jobs/using-concurrency
#   https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{github.ref_name}}-${{github.repository}}
  cancel-in-progress: true

jobs:
  validate_gradle_wrapper:
    name: "Gradle Wrapper"
    uses: ./.github/workflows/call-gradle-wrapper-validation.yml
  run_detekt:
    name: "Detekt"
    needs: validate_gradle_wrapper
    uses: ./.github/workflows/call-detekt-validation.yml
  run_unit_tests:
    name: "Tests"
    needs: validate_gradle_wrapper
    uses: ./.github/workflows/call-tests-validation.yml
