name: "Upload GitHub Release"
on:
  workflow_call:
    secrets:
      ACTIONS_TOKEN:
        required: true
jobs:
  upload_github_release:
    name: "Upload GitHub Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Read Project Properties"
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './gradle.properties'
          properties: 'klibs.project.name klibs.project.version.string'

      - name: "Download android-apk"
        uses: actions/download-artifact@d0ce8fd1167ed839810201de977912a090ab10a7
        with:
          name: android-apk
          path: ./artifacts

      - name: "Download wear-apk"
        uses: actions/download-artifact@d0ce8fd1167ed839810201de977912a090ab10a7
        with:
          name: wear-apk
          path: ./artifacts

      - name: "Create GitHub Release"
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          files: |
            ./artifacts/*.apk
          tag_name: ${{ steps.properties.outputs.klibs-project-version-string }}
          name: ${{ steps.properties.outputs.klibs-project-name }} - ${{ steps.properties.outputs.klibs-project-version-string }}
          draft: false
          prerelease: false
